CREATE TYPE "public"."gear_type" AS ENUM('CAMERA', 'LENS');--> statement-breakpoint
CREATE TABLE "sharply_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "sharply_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "brands" (
	"id" varchar(24) PRIMARY KEY DEFAULT gen_random_uuid()::text NOT NULL,
	"name" varchar(200) NOT NULL,
	"slug" varchar(200) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "brands_name_unique" UNIQUE("name"),
	CONSTRAINT "brands_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "gear" (
	"id" varchar(24) PRIMARY KEY DEFAULT gen_random_uuid()::text NOT NULL,
	"slug" varchar(220) NOT NULL,
	"search_name" text NOT NULL,
	"name" varchar(240) NOT NULL,
	"gear_type" "gear_type" NOT NULL,
	"brand_id" varchar(24) NOT NULL,
	"mount_id" varchar(24),
	"release_date" timestamp with time zone,
	"price_usd" numeric(10, 2),
	"thumbnail_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "gear_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "mounts" (
	"id" varchar(24) PRIMARY KEY DEFAULT gen_random_uuid()::text NOT NULL,
	"name" varchar(200) NOT NULL,
	"slug" varchar(200) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "mounts_name_unique" UNIQUE("name"),
	CONSTRAINT "mounts_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "sharply_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sharply_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sensor_formats" (
	"id" varchar(24) PRIMARY KEY DEFAULT gen_random_uuid()::text NOT NULL,
	"name" varchar(200) NOT NULL,
	"slug" varchar(200) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "sensor_formats_name_unique" UNIQUE("name"),
	CONSTRAINT "sensor_formats_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "sharply_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sharply_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "sharply_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "sharply_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "sharply_account" ADD CONSTRAINT "sharply_account_userId_sharply_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."sharply_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gear" ADD CONSTRAINT "gear_brand_id_brands_id_fk" FOREIGN KEY ("brand_id") REFERENCES "public"."brands"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gear" ADD CONSTRAINT "gear_mount_id_mounts_id_fk" FOREIGN KEY ("mount_id") REFERENCES "public"."mounts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sharply_post" ADD CONSTRAINT "sharply_post_createdById_sharply_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."sharply_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sharply_session" ADD CONSTRAINT "sharply_session_userId_sharply_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."sharply_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "sharply_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "gear_search_idx" ON "gear" USING btree ("search_name");--> statement-breakpoint
CREATE INDEX "gear_type_brand_idx" ON "gear" USING btree ("gear_type","brand_id");--> statement-breakpoint
CREATE INDEX "gear_brand_mount_idx" ON "gear" USING btree ("brand_id","mount_id");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "sharply_post" USING btree ("createdById");--> statement-breakpoint
CREATE INDEX "name_idx" ON "sharply_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "t_user_id_idx" ON "sharply_session" USING btree ("userId");