CREATE TYPE "public"."bingo_board_status" AS ENUM('ACTIVE', 'COMPLETED', 'EXPIRED', 'ARCHIVED');--> statement-breakpoint
CREATE TYPE "public"."bingo_event_type" AS ENUM('tile_completed', 'submission_created', 'score_updated', 'board_completed', 'board_expired', 'board_created', 'inactivity_timer_started', 'inactivity_timer_extended');--> statement-breakpoint
CREATE TABLE "app"."bingo_board_tiles" (
	"id" varchar(36) PRIMARY KEY DEFAULT gen_random_uuid()::text NOT NULL,
	"board_id" varchar(36) NOT NULL,
	"position" integer NOT NULL,
	"label" text NOT NULL,
	"is_free_tile" boolean DEFAULT false NOT NULL,
	"completed_by_user_id" varchar(255),
	"completed_submission_id" varchar(36),
	"completed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."bingo_boards" (
	"id" varchar(36) PRIMARY KEY DEFAULT gen_random_uuid()::text NOT NULL,
	"status" "bingo_board_status" DEFAULT 'ACTIVE' NOT NULL,
	"inactivity_duration_seconds" integer DEFAULT 14400 NOT NULL,
	"expires_at" timestamp with time zone,
	"first_completed_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"expired_at" timestamp with time zone,
	"end_reason" varchar(30),
	"created_by_user_id" varchar(255),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."bingo_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "app"."bingo_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type" "bingo_event_type" NOT NULL,
	"board_id" varchar(36) NOT NULL,
	"board_tile_id" varchar(36),
	"submission_id" varchar(36),
	"user_id" varchar(255),
	"payload" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."bingo_scores" (
	"id" varchar(36) PRIMARY KEY DEFAULT gen_random_uuid()::text NOT NULL,
	"board_id" varchar(36) NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"points" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app"."bingo_submissions" (
	"id" varchar(36) PRIMARY KEY DEFAULT gen_random_uuid()::text NOT NULL,
	"board_id" varchar(36) NOT NULL,
	"board_tile_id" varchar(36),
	"user_id" varchar(255) NOT NULL,
	"discord_message_url" text NOT NULL,
	"discord_guild_id" varchar(50),
	"discord_channel_id" varchar(50),
	"discord_message_id" varchar(50),
	"validation_passed" boolean DEFAULT true NOT NULL,
	"validation_metadata" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "app"."bingo_board_tiles" ADD CONSTRAINT "bingo_board_tiles_board_id_bingo_boards_id_fk" FOREIGN KEY ("board_id") REFERENCES "app"."bingo_boards"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."bingo_board_tiles" ADD CONSTRAINT "bingo_board_tiles_completed_by_user_id_user_id_fk" FOREIGN KEY ("completed_by_user_id") REFERENCES "app"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."bingo_board_tiles" ADD CONSTRAINT "bingo_board_tiles_completed_submission_id_bingo_submissions_id_fk" FOREIGN KEY ("completed_submission_id") REFERENCES "app"."bingo_submissions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."bingo_boards" ADD CONSTRAINT "bingo_boards_created_by_user_id_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "app"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."bingo_events" ADD CONSTRAINT "bingo_events_board_id_bingo_boards_id_fk" FOREIGN KEY ("board_id") REFERENCES "app"."bingo_boards"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."bingo_events" ADD CONSTRAINT "bingo_events_board_tile_id_bingo_board_tiles_id_fk" FOREIGN KEY ("board_tile_id") REFERENCES "app"."bingo_board_tiles"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."bingo_events" ADD CONSTRAINT "bingo_events_submission_id_bingo_submissions_id_fk" FOREIGN KEY ("submission_id") REFERENCES "app"."bingo_submissions"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."bingo_events" ADD CONSTRAINT "bingo_events_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "app"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."bingo_scores" ADD CONSTRAINT "bingo_scores_board_id_bingo_boards_id_fk" FOREIGN KEY ("board_id") REFERENCES "app"."bingo_boards"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."bingo_scores" ADD CONSTRAINT "bingo_scores_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "app"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."bingo_submissions" ADD CONSTRAINT "bingo_submissions_board_id_bingo_boards_id_fk" FOREIGN KEY ("board_id") REFERENCES "app"."bingo_boards"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app"."bingo_submissions" ADD CONSTRAINT "bingo_submissions_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "app"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "bingo_board_tiles_board_position_uq" ON "app"."bingo_board_tiles" USING btree ("board_id","position");--> statement-breakpoint
CREATE INDEX "bingo_board_tiles_board_completed_idx" ON "app"."bingo_board_tiles" USING btree ("board_id","completed_at");--> statement-breakpoint
CREATE INDEX "bingo_boards_status_idx" ON "app"."bingo_boards" USING btree ("status");--> statement-breakpoint
CREATE INDEX "bingo_boards_created_idx" ON "app"."bingo_boards" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "bingo_events_board_idx" ON "app"."bingo_events" USING btree ("board_id");--> statement-breakpoint
CREATE INDEX "bingo_events_board_id_idx" ON "app"."bingo_events" USING btree ("board_id","id");--> statement-breakpoint
CREATE INDEX "bingo_events_created_idx" ON "app"."bingo_events" USING btree ("created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "bingo_scores_board_user_uq" ON "app"."bingo_scores" USING btree ("board_id","user_id");--> statement-breakpoint
CREATE INDEX "bingo_scores_board_points_idx" ON "app"."bingo_scores" USING btree ("board_id","points");--> statement-breakpoint
CREATE INDEX "bingo_submissions_board_idx" ON "app"."bingo_submissions" USING btree ("board_id");--> statement-breakpoint
CREATE INDEX "bingo_submissions_user_idx" ON "app"."bingo_submissions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "bingo_submissions_tile_idx" ON "app"."bingo_submissions" USING btree ("board_tile_id");--> statement-breakpoint
CREATE INDEX "bingo_submissions_created_idx" ON "app"."bingo_submissions" USING btree ("created_at");