export const BINGO_GRID_SIZE = 5;
export const BINGO_TILE_COUNT = BINGO_GRID_SIZE * BINGO_GRID_SIZE;
export const BINGO_FREE_TILE_INDEX = 12;
export const BINGO_FREE_TILE_LABEL = "Free Tile";
export const BINGO_DEFAULT_INACTIVITY_SECONDS = 4 * 60 * 60;
export const BINGO_POLL_INTERVAL_MS = 5_000;

export const BINGO_TEMPLATE_LABELS = [
  "More megapixels is better",
  "Photoshop/editing is cheating",
  "AI Art",
  "Multiple phone images to critique",
  "asks for feedback > gets defensive",
  "HDR Confusion",
  "Discord ruined my image",
  "Everything, Video and some birds with $400 budget",
  "My phone has a 48/64/108 MP camera",
  "Snapshot for critique",
  "It's an artistic choice!",
  "Pasta",
  "Stuck on shit advice from family or friend",
  "Stuck on influencer gear rec",
  "Wants a mirrorless camera for no reason",
  "Is this a good beginner camera? [Insert Canon Rebel here]",
  "I don't have a budget",
  "Wants a full frame camera for no reason",
  "Wants Sony/Fuji for no reason",
  "Source check: Trust me bro",
  "What camera can I get to make really high quality images",
  "What camera makes vintage/retro photos?",
  "Specialists disagree",
  "Is X camera good? > 10 hours later > Is Y camera good?",
  "I'm scared of used",
  "TikTok/reels advice",
  "Car photography",
  "Nikon people pushing Nikon",
  "Nikon racism",
  "Sigma 150-600",
  "Sigma 100-400",
  "600mm f/4 rec",
  "400mm f/2.8 rec",
  "Someone refuses to use prime lenses",
  "Someone refuses to use zoom lenses",
  "ZVE10 rec",
  "This server is so elitist",
  "Un-straightened photo in feedback channel",
  "Are these presets worth [insert cost]",
  "Quag emoji",
  "But [insert Youtuber] said...",
  "Selling camera to buy a worse camera",
  "What lens should I get?",
  "I heard Nikon isn't good.",
  "Source = TikTok/Reels/Shorts",
  "Photography is so expensive!",
  "Largest lens topic",
  "TV lens reference",
  "Most expensive lens topic",
  "Out-of-context 'Just buy [some expensive camera/lens]'",
  "'I'm planning to get A6400'",
  "Skull emoji",
  ":sob: emoji",
  "Wilted rose emoji",
  "Leica mentioned",
  "Sony & Car Rollers",
  "Sony has a big lens selection",
  "Wants Z9 for no reason",
  "Is A7ii good?/worth ____?",
  "Mousepad/Keyboard discussion"
] as const;
