/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    news: News;
    review: Review;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    review: ReviewSelect<false> | ReviewSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  _key?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  /**
   * The title of the news article.
   */
  title: string;
  /**
   * The thumbnail of the news article.
   */
  thumbnail: number | Media;
  /**
   * Override the date of the news article. Defaults to creation date if not set.
   */
  override_date?: string | null;
  /**
   * Auto-generated from title.
   */
  slug?: string | null;
  /**
   * The excerpt of the news article. Auto-generated from content.
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Select the brand associated with this article
   */
  related_brand?: string | null;
  /**
   * Indicate which gear items have been mentioned in this news article.
   */
  related_gear_items?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Add any source links to the news article.
   */
  sourceLinks?:
    | {
        name?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review".
 */
export interface Review {
  id: number;
  /**
   * The title of the review.
   */
  title: string;
  /**
   * The thumbnail of the review.
   */
  thumbnail: number | Media;
  /**
   * Auto-generated from title, can be overridden
   */
  slug?: string | null;
  review_gear_item: string;
  /**
   * A relatively short overview/summary/conclusion based on your experience and findings. You will go more in depth below about specific features. Keep this surface level, and focus on how it compares to both the competition and other relevant items from the same manufacturer. This will be shown as the description/excerpt of the review.
   */
  review_summary: string;
  /**
   * Add some good things you discovered/experienced with the item.
   */
  goodPoints: {
    goodNote: string;
    id?: string | null;
  }[];
  /**
   * Add some bad things you discovered/experienced with the item.
   */
  badPoints: {
    badNote: string;
    id?: string | null;
  }[];
  /**
   * This is where you can add a detailed explanation of how you used the item, your experience, and specific perks and flaws you found. Recommended structure: Start with a description of what you used it for, your first impression of the build quality and performance, and an explanation of how it worked for your needs/use case. Then discuss whether you would recommend this item to others, who you would recommended it to, and who it might not be right for.
   */
  reviewContent: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Provide ratings only for the genres that apply. Leave unselected when not applicable.
   */
  genreRatings?: {
    /**
     * Wedding photography
     */
    weddings?: ('0' | '1' | '2' | '3') | null;
    /**
     * Fast action and sports
     */
    sports?: ('0' | '1' | '2' | '3') | null;
    /**
     * Animals, birds, and other creatures.
     */
    wildlife?: ('0' | '1' | '2' | '3') | null;
    /**
     * Street and candid
     */
    street?: ('0' | '1' | '2' | '3') | null;
    /**
     * Travel and documentary
     */
    travel?: ('0' | '1' | '2' | '3') | null;
    /**
     * Landscapes and nature
     */
    landscape?: ('0' | '1' | '2' | '3') | null;
    /**
     * Video and filmmaking
     */
    video?: ('0' | '1' | '2' | '3') | null;
    /**
     * Products and food photography
     */
    'product-food'?: ('0' | '1' | '2' | '3') | null;
    /**
     * Events and concerts
     */
    events?: ('0' | '1' | '2' | '3') | null;
    /**
     * Portraits of people; senior portraits, engagement shoots, models, fashion photography, etc.
     */
    portraits?: ('0' | '1' | '2' | '3') | null;
    /**
     * Photos of the milky way, stars, the moon, or other celestial bodies
     */
    astro?: ('0' | '1' | '2' | '3') | null;
    architecture?: ('0' | '1' | '2' | '3') | null;
    fashion?: ('0' | '1' | '2' | '3') | null;
  };
  genreRatingsMap?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Add any source links to the review.
   */
  sourceLinks?:
    | {
        name?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'review';
        value: number | Review;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _key?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  thumbnail?: T;
  override_date?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  related_brand?: T;
  related_gear_items?: T;
  sourceLinks?:
    | T
    | {
        name?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review_select".
 */
export interface ReviewSelect<T extends boolean = true> {
  title?: T;
  thumbnail?: T;
  slug?: T;
  review_gear_item?: T;
  review_summary?: T;
  goodPoints?:
    | T
    | {
        goodNote?: T;
        id?: T;
      };
  badPoints?:
    | T
    | {
        badNote?: T;
        id?: T;
      };
  reviewContent?: T;
  genreRatings?:
    | T
    | {
        weddings?: T;
        sports?: T;
        wildlife?: T;
        street?: T;
        travel?: T;
        landscape?: T;
        video?: T;
        'product-food'?: T;
        events?: T;
        portraits?: T;
        astro?: T;
        architecture?: T;
        fashion?: T;
      };
  genreRatingsMap?: T;
  sourceLinks?:
    | T
    | {
        name?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}